#!/usr/bin/env python3
"""Configure Wi-Fi, render firmware defaults, and flash Xiao ESP32-C6.

Prereqs:
- arduino-cli installed and on PATH
- esp32 core + Adafruit SSD1306/GFX libs installed
- USB cable attached to Xiao ESP32-C6

Example:
  python3 tools/beacon_flash.py --ssid MyNet --password Secret123 \
      --port /dev/tty.usbmodemXYZ
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FW_DIR = ROOT / "firmware" / "beacon_wifi"
CRED_TEMPLATE = FW_DIR / "wifi_credentials.h.example"
CRED_TARGET = FW_DIR / "wifi_credentials.h"
FQBN = os.environ.get("ARDUINO_FQBN", "esp32:esp32:xiao_esp32c6")


def write_credentials(ssid: str, password: str, name: str) -> None:
    content = [
        "#pragma once",
        "// Auto-generated by beacon_flash.py",
        f'#define WIFI_SSID_DEFAULT "{ssid}"',
        f'#define WIFI_PASS_DEFAULT "{password}"',
        f'#define BEACON_NAME_DEFAULT "{name}"',
        "",
    ]
    CRED_TARGET.write_text("\n".join(content), encoding="utf-8")
    print(f"[ok] Wrote {CRED_TARGET}")


def run(cmd: list[str]) -> None:
    print("[cmd]", " ".join(cmd))
    subprocess.run(cmd, check=True)


def ensure_cli() -> None:
    if shutil.which("arduino-cli"):
        return
    raise SystemExit("arduino-cli not found on PATH. Install from https://arduino.github.io/arduino-cli/latest/ and retry.")


def validate_cli_value(value: str, label: str, pattern: str) -> str:
    if not value or not re.fullmatch(pattern, value):
        raise SystemExit(f"Invalid {label}: {value!r}")
    return value


def flash(args: argparse.Namespace) -> None:
    ensure_cli()
    if not CRED_TARGET.exists():
        raise SystemExit(f"wifi_credentials.h missing; expected at {CRED_TARGET}")

    safe_fqbn = validate_cli_value(FQBN, "FQBN", r"[A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+")
    safe_port = validate_cli_value(args.port, "serial port", r"[A-Za-z0-9_./:-]+")

    build_dir = FW_DIR
    compile_cmd = ["arduino-cli", "compile", "--fqbn", safe_fqbn, str(build_dir)]
    run(compile_cmd)

    upload_cmd = [
        "arduino-cli",
        "upload",
        "--fqbn",
        safe_fqbn,
        "-p",
        safe_port,
        str(build_dir),
    ]
    run(upload_cmd)
    print("[done] Flash complete")


def main() -> None:
    parser = argparse.ArgumentParser(description="Flash Xiao ESP32-C6 IR Beacon firmware")
    parser.add_argument("--ssid", required=True, help="Wi-Fi SSID for STA mode")
    parser.add_argument("--password", required=True, help="Wi-Fi password for STA mode")
    parser.add_argument("--port", required=True, help="Serial port (e.g., /dev/tty.usbmodemXYZ or COM5)")
    parser.add_argument("--name", required=False, default="Beacon", help="Display name to show on the beacon screen")
    args = parser.parse_args()

    if not CRED_TEMPLATE.exists():
        raise SystemExit(f"Template missing: {CRED_TEMPLATE}")

    try:
        write_credentials(args.ssid, args.password, args.name)
        flash(args)
    finally:
        if CRED_TARGET.exists():
            CRED_TARGET.unlink()
            print(f"[cleanup] Removed {CRED_TARGET}")


if __name__ == "__main__":
    main()
